---
- id: "TEAM1"
  name: "Team 1"
  config:
    croissantDay: 5
    nbPerDay: 1
  members:
  - name: "test"
    forename: "toto"
    mail: "toto@email.com"
    date: 1577836800000
    isActive: true
    didBringCroissants: false
  - name: "titi"
    forename: ""
    mail: "titi@email.com"
    date: null
    isActive: true
    didBringCroissants: false
- id: "TEAM2"
  name: "Team 2"
  config:
    croissantDay: 5
    nbPerDay: 1
  members:
  - name: "test1"
    forename: "test1"
    mail: "test1@hotmail.com"
    date: 1555686996888
    isActive: true
    didBringCroissants: false
